added special handling for frontends logs

diff --git a/RetrieveLogs b/RetrieveLogs
--- a/RetrieveLogs
+++ b/RetrieveLogs
@@ -3,9 +3,10 @@
 ### Utilitarian script to retrieve log files from the cmsweb machines and
 ### copy it under your own work AFS public area, with the correct permissions.
 ###
-### Usage: retrieveLogs -h
-### Usage: retrieveLogs -s <service> -f <file name> -n <"list of hosts space separated"> -d <dirName> -a <AFS user>
-### Usage: Example: retrieveLogs -s phedex -f error_log_20131122.txt -n "vocms132 vocms133" -d forTony -a xblahx
+### Usage: RetrieveLogs -h
+### Usage: RetrieveLogs -s <service> -f <file name> -n <"list of hosts space separated"> -d <dirName> -a <AFS user> [-p <pattern for frontend>] 
+### Usage: Example: RetrieveLogs -s phedex -f error_log_20131122.txt -n "vocms132 vocms133" -d forTony -a xblahx
+### Usage: Example: RetrieveLogs -s frontend -f access_log_20131124.txt -n "vocms134 vocms135" -d forAlan -a xblahblahx -p gitweb
 
 usage()
 {
@@ -34,21 +35,29 @@ setupDir()
   fs la /afs/cern.ch/work/a/${USER}/public/$NEWDIR
 }
 
+### Print some information to the user
+info()
+{
+  echo; echo "Hosts: $NODES"
+  echo "Files: $FILE"
+  echo "  from: /data/srv/logs/${SERVICE}/"
+  echo "  to:   /afs/cern.ch/work/a/${USER}/public/${NEWDIR}"; 
+  if [ "$SERVICE" == "frontend" ]; then
+    echo "Provided pattern for frontends: $PATTERN"
+  fi
+  echo
+}
+
 ### Access the vocmsXXX machines and get the file size, if the user
 ### accepts it to be transferred, then it copies the file to the dir
 ### previously created and append the hostname to it
 getLogs()
 {
-  echo; echo "Hosts: $NODES"
-  echo "Files: $FILE"
-  echo "  from: /data/srv/logs/${SERVICE}/"
-  echo "  to:   /afs/cern.ch/work/a/${USER}/public/${NEWDIR}"; echo
-
   for f in $FILE; do
     for n in $NODES; do
       result=`ssh ${USER}@${n}.cern.ch "ls -lh /data/srv/logs/${SERVICE}/${f}"`
       if [ $? != "0" ]; then
-        echo "$n : File not found!"
+        echo "$n -- $f : File not found!"
         continue
       fi
   
@@ -64,6 +73,39 @@ getLogs()
   done
 }
 
+### Access the vocmsXXX machines, grep the file for pattern and write the
+### output to /tmp/. Then it gets the size of the new file in /tmp
+### and you can (or not) copy it to your afs area.
+getFrontendLogs()
+{
+  for f in $FILE; do
+    for n in $NODES; do
+      echo "Grepping $f for '$PATTERN', it may take some minutes ..." 
+      ssh ${USER}@${n}.cern.ch "grep -Isi '${PATTERN}' /data/srv/logs/${SERVICE}/${f} > /tmp/${f}_$n"
+      if [ $? != "0" ]; then
+        echo "$n -- $f : File not found!"
+        continue
+      fi
+
+      result=`ssh ${USER}@${n}.cern.ch "ls -lh /tmp/${f}_$n"`
+      if [ $? != "0" ]; then
+        echo "$n -- $f_$n : Your pattern did *not* match anything!"
+        continue
+      fi  
+
+      fileSize=`echo $result | grep tmp | awk '{print $5}'`
+      echo "Checking size on $n : $fileSize bytes"
+      read -p "Continue (y/n)? " choice
+      case "$choice" in 
+        y|Y ) true;;
+        * ) echo "no"; continue;;
+      esac
+      scp ${USER}@${n}.cern.ch:/tmp/${f}_$n /afs/cern.ch/work/a/${USER}/public/${NEWDIR}
+      echo
+    done
+  done
+}
+
 for arg; do
   case $arg in
     -h) help ;;
@@ -72,10 +114,24 @@ for arg; do
     -n) NODES=$2; shift; shift ;;
     -d) NEWDIR=$2; shift; shift ;;
     -a) AFSUSER=$2; shift; shift ;;
+    -p) PATTERN=$2; shift; shift ;;
     -*) usage ;;
   esac
 done
 
 setupDir
-getLogs
+
+if [ "$SERVICE" == "frontend" ]; then
+  if [ -z "$PATTERN" ]; then
+    echo "You *must* provide an access pattern to the frontend logs!"
+    usage
+  else
+    info
+    getFrontendLogs
+  fi
+else
+  info
+  getLogs
+fi
+
 exit 0
